version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run:
          name: Check Yarn Version
          command: yarn -v
      - store_artifacts:
          path: ~/tests/test_artifacts
          destination: yarn-version
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          name: Run Tests
          command: yarn test
      - store_artifacts:
          path: ~/tests/test_artifacts
          destination: yarn-test
      - store_test_results:
          path: test-results

workflows:
  run-tests-workflow:
    jobs:
      - build